export const ACTIONS = {
    // Task
    ADD_TASK: 'ADD_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    TOGGLE_TASK_DONE: 'TOGGLE_TASK_DONE',

    // Project
    ADD_PROJECT: 'ADD_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',

    // UI
    SET_FILTER: 'SET_FILTER',
    TOGGLE_SHOW_DONE: 'TOGGLE_SHOW_DONE',

    // Storage
    LOAD_FROM_STORAGE: 'LOAD_FROM_STORAGE',
} as const;
